#!/bin/bash

ps -axm -o %mem,rss,pid,comm | grep "Google Drive\
\|JetBrains Toolbox\
\|ZoomOpener\
\|wunderkinder\
\|Skype Helper\
\|docker\
\|Jing\
\|Avira\	
\|DrCleaner\
\|onepassword\
\|expressvpnd"
